name: Build/release Electron app

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the release (e.g., v1.0.0)'
        required: false
        default: ''

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.4.0

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd libarchive-tools dpkg rpm fakeroot
          sudo snap install snapcraft --classic

      - name: Set permissions for app-builder
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x node_modules/app-builder-bin/linux/x64/app-builder

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        timeout-minutes: 30
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ELECTRON_BUILDER_LOG_LEVEL: debug
          ELECTRON_MIRROR: https://github.com/electron/electron/releases/download/
        run: |
          export ELECTRON_BUILDER_LOGGING=1
          pnpm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: pnpm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: pnpm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ github.event.inputs.version || format('manual-release-{0}', github.run_id) }}
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
